version: '3.7'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./docker
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  composer:
    image: composer:1.10.22
    volumes:
      - ./:/code
    working_dir: /code
    entrypoint: ["composer", "--ignore-platform-reqs"]
    profiles: [ "ignore" ]